<?php
/**
 * Raven API Framework.
 * Copyright 2024 Enicore Solutions.
 */
namespace Enicore\RavenApi;

use GeoIp2\Database\Reader;

/**
 * The Countries class manages a static list of countries and their corresponding country codes. It provides methods to
 * access the list of countries, check if a country exists by its ID, and retrieve the country name by its ID.
 *
 * This class is used to provide country-related functionality for various parts of the application.
 *
 * @package Enicore\RavenApi
 */
class Countries
{
    /**
     * An associative array mapping ISO 3166-1 country codes to country names.
     */
    private static array $countries = [
        'AU' => 'Australia',
        'CN' => 'China',
        'IN' => 'India',
        'MY' => 'Malaysia',
        'KR' => 'Korea, Republic of',
        'JP' => 'Japan',
        'TW' => 'Taiwan',
        'HK' => 'Hong Kong',
        'TH' => 'Thailand',
        'VN' => 'Vietnam',
        'FR' => 'France',
        'EU' => 'Europe',
        'DE' => 'Germany',
        'SE' => 'Sweden',
        'IT' => 'Italy',
        'ES' => 'Spain',
        'AT' => 'Austria',
        'GB' => 'United Kingdom',
        'AE' => 'United Arab Emirates',
        'IL' => 'Israel',
        'UA' => 'Ukraine',
        'RU' => 'Russian Federation',
        'KZ' => 'Kazakhstan',
        'PT' => 'Portugal',
        'GR' => 'Greece',
        'SA' => 'Saudi Arabia',
        'DK' => 'Denmark',
        'IR' => 'Iran, Islamic Republic of',
        'NO' => 'Norway',
        'US' => 'United States',
        'CA' => 'Canada',
        'MX' => 'Mexico',
        'BM' => 'Bermuda',
        'PR' => 'Puerto Rico',
        'VI' => 'Virgin Islands, U.S.',
        'BO' => 'Bolivia',
        'NL' => 'Netherlands',
        'NZ' => 'New Zealand',
        'SG' => 'Singapore',
        'ID' => 'Indonesia',
        'NP' => 'Nepal',
        'PH' => 'Philippines',
        'PG' => 'Papua New Guinea',
        'PK' => 'Pakistan',
        'BS' => 'Bahamas',
        'VC' => 'Saint Vincent and the Grenadines',
        'CL' => 'Chile',
        'NC' => 'New Caledonia',
        'AR' => 'Argentina',
        'DM' => 'Dominica',
        'BD' => 'Bangladesh',
        'TK' => 'Tokelau',
        'KH' => 'Cambodia',
        'MO' => 'Macau',
        'MV' => 'Maldives',
        'AF' => 'Afghanistan',
        'FJ' => 'Fiji',
        'MN' => 'Mongolia',
        'WF' => 'Wallis and Futuna',
        'BE' => 'Belgium',
        'AL' => 'Albania',
        'CY' => 'Cyprus',
        'PL' => 'Poland',
        'LU' => 'Luxembourg',
        'CH' => 'Switzerland',
        'HU' => 'Hungary',
        'EE' => 'Estonia',
        'BY' => 'Belarus',
        'SK' => 'Slovakia',
        'LV' => 'Latvia',
        'PS' => 'Palestinian Territory, Occupied',
        'IQ' => 'Iraq',
        'FI' => 'Finland',
        'TR' => 'Turkey',
        'CZ' => 'Czech Republic',
        'KG' => 'Kyrgyzstan',
        'MD' => 'Moldova, Republic of',
        'YE' => 'Yemen',
        'BG' => 'Bulgaria',
        'RO' => 'Romania',
        'LT' => 'Lithuania',
        'HR' => 'Croatia',
        'BA' => 'Bosnia and Herzegovina',
        'AM' => 'Armenia',
        'GE' => 'Georgia',
        'UZ' => 'Uzbekistan',
        'IE' => 'Ireland',
        'AZ' => 'Azerbaijan',
        'JE' => 'Jersey',
        'AN' => 'Netherlands Antilles',
        'BZ' => 'Belize',
        'BR' => 'Brazil',
        'ZA' => 'South Africa',
        'EG' => 'Egypt',
        'NG' => 'Nigeria',
        'TZ' => 'Tanzania, United Republic of',
        'ZM' => 'Zambia',
        'SN' => 'Senegal',
        'MG' => 'Madagascar',
        'AO' => 'Angola',
        'NA' => 'Namibia',
        'CI' => 'Cote D\'Ivoire',
        'GH' => 'Ghana',
        'SD' => 'Sudan',
        'CM' => 'Cameroon',
        'MW' => 'Malawi',
        'KE' => 'Kenya',
        'GA' => 'Gabon',
        'ML' => 'Mali',
        'BJ' => 'Benin',
        'TD' => 'Chad',
        'BW' => 'Botswana',
        'LY' => 'Libyan Arab Jamahiriya',
        'CV' => 'Cape Verde',
        'RW' => 'Rwanda',
        'CG' => 'Congo',
        'UG' => 'Uganda',
        'MZ' => 'Mozambique',
        'GM' => 'Gambia',
        'LS' => 'Lesotho',
        'MU' => 'Mauritius',
        'ZW' => 'Zimbabwe',
        'BF' => 'Burkina Faso',
        'SL' => 'Sierra Leone',
        'SO' => 'Somalia',
        'CD' => 'Congo, The Democratic Republic of the',
        'NE' => 'Niger',
        'CF' => 'Central African Republic',
        'SZ' => 'Swaziland',
        'TG' => 'Togo',
        'GN' => 'Guinea',
        'LR' => 'Liberia',
        'SC' => 'Seychelles',
        'MA' => 'Morocco',
        'DZ' => 'Algeria',
        'MR' => 'Mauritania',
        'DJ' => 'Djibouti',
        'KM' => 'Comoros',
        'RE' => 'Reunion',
        'GQ' => 'Equatorial Guinea',
        'TN' => 'Tunisia',
        'MT' => 'Malta',
        'NI' => 'Nicaragua',
        'RS' => 'Serbia',
        'LB' => 'Lebanon',
        'SI' => 'Slovenia',
        'TJ' => 'Tajikistan',
        'IS' => 'Iceland',
        'JO' => 'Jordan',
        'MK' => 'Macedonia',
        'ME' => 'Montenegro',
        'GI' => 'Gibraltar',
        'VA' => 'Holy See (Vatican City State)',
        'LI' => 'Liechtenstein',
        'IM' => 'Isle of Man',
        'CR' => 'Costa Rica',
        'PA' => 'Panama',
        'CU' => 'Cuba',
        'KY' => 'Cayman Islands',
        'JM' => 'Jamaica',
        'VG' => 'Virgin Islands, British',
        'CO' => 'Colombia',
        'GT' => 'Guatemala',
        'MH' => 'Marshall Islands',
        'PE' => 'Peru',
        'AQ' => 'Antarctica',
        'QA' => 'Qatar',
        'BB' => 'Barbados',
        'AW' => 'Aruba',
        'MC' => 'Monaco',
        'KW' => 'Kuwait',
        'OM' => 'Oman',
        'AI' => 'Anguilla',
        'KN' => 'Saint Kitts and Nevis',
        'GD' => 'Grenada',
        'DO' => 'Dominican Republic',
        'PY' => 'Paraguay',
        'LC' => 'Saint Lucia',
        'GL' => 'Greenland',
        'KP' => 'Korea, Democratic People\'s Republic of',
        'VE' => 'Venezuela',
        'TC' => 'Turks and Caicos Islands',
        'AG' => 'Antigua and Barbuda',
        'BH' => 'Bahrain',
        'TV' => 'Tuvalu',
        'PF' => 'French Polynesia',
        'SB' => 'Solomon Islands',
        'VU' => 'Vanuatu',
        'ER' => 'Eritrea',
        'TT' => 'Trinidad and Tobago',
        'AD' => 'Andorra',
        'SY' => 'Syrian Arab Republic',
        'HT' => 'Haiti',
        'EC' => 'Ecuador',
        'SH' => 'Saint Helena',
        'FM' => 'Micronesia, Federated States of',
        'SV' => 'El Salvador',
        'HN' => 'Honduras',
        'UY' => 'Uruguay',
        'LK' => 'Sri Lanka',
        'AX' => 'Aland Islands',
        'AS' => 'American Samoa',
        'FO' => 'Faroe Islands',
        'GG' => 'Guernsey',
        'SM' => 'San Marino',
        'SJ' => 'Svalbard and Jan Mayen',
        'TM' => 'Turkmenistan',
        'GU' => 'Guam',
        'NU' => 'Niue',
        'MM' => 'Myanmar',
        'BN' => 'Brunei Darussalam',
        'FK' => 'Falkland Islands (Malvinas)',
        'UM' => 'United States Minor Outlying Islands',
        'BV' => 'Bouvet Island',
        'CK' => 'Cook Islands',
        'WS' => 'Samoa',
        'GF' => 'French Guiana',
        'MP' => 'Northern Mariana Islands',
        'PW' => 'Palau',
        'LA' => 'Lao People\'s Democratic Republic',
        'GY' => 'Guyana',
        'SR' => 'Suriname',
        'MS' => 'Montserrat',
        'MQ' => 'Martinique',
        'PM' => 'Saint Pierre and Miquelon',
        'GP' => 'Guadeloupe',
        'MF' => 'Saint Martin',
        'BI' => 'Burundi',
        'ET' => 'Ethiopia',
        'BT' => 'Bhutan',
        'IO' => 'British Indian Ocean Territory',
        'GW' => 'Guinea-Bissau',
        'TO' => 'Tonga',
        'TL' => 'Timor-Leste',
        'ST' => 'Sao Tome and Principe',
        'KI' => 'Kiribati',
        'NF' => 'Norfolk Island',
        'NR' => 'Nauru',
        'YT' => 'Mayotte',
        'EH' => 'Western Sahara',
        'CX' => 'Christmas Island',
        'TF' => 'French Southern Territories',
        'PN' => 'Pitcairn Islands',
        'CC' => 'Cocos (Keeling) Islands',
        'GS' => 'South Georgia and the South Sandwich Islands',
        'BL' => 'Saint Barthelemy',
        'BQ' => 'Bonaire, Saint Eustatius and Saba',
        'CW' => 'Curacao',
        'SS' => 'South Sudan',
        'SX' => 'Sint Maarten (Dutch part)',
        'XK' => 'Kosovo',
        'XX' => 'Unknown',
        '' => 'Unknown',
    ];

    /**
     * Gets the full list of countries.
     *
     * @return array<string, string> An associative array of country codes and their corresponding country names.
     */
    public static function getAllCountries(): array
    {
        return self::$countries;
    }

    /**
     * Checks if a country exists in the country list based on its country code.
     *
     * @param string $countryId The country code to check (e.g., "US", "ES").
     * @return bool True if the country exists, false otherwise.
     */
    public static function countryExists(string $countryId): bool
    {
        return array_key_exists(strtoupper($countryId), self::$countries);
    }

    /**
     * Gets the country name by its country code.
     *
     * @param string $countryId The country code (e.g., "US", "ES").
     * @return string The name of the country if it exists, or an empty string if it doesn't.
     */
    public static function getCountryName(string $countryId): string
    {
        $countryId = strtoupper($countryId);

        return self::countryExists($countryId) ? self::$countries[$countryId] : '';
    }
}
